server:
  port: 80

spring:
  profiles:
    active: dev
  application:
    name: copy-share-wall

  datasource:
    url: jdbc:mysql://101.200.202.11:3306/wallcopy?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '082264'

mybatis-plus:
  mapper-locations: classpath:com/asja/corewall/mapper/xml/*.xml